// <auto-generated />
using FantasyApp.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FantasyApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241229165529_m")]
    partial class m
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FantasyApp.Models.Druzyna", b =>
                {
                    b.Property<int>("DruzynaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DruzynaId"), 1L, 1);

                    b.Property<int>("Budzet")
                        .HasColumnType("int");

                    b.Property<string>("NazwaDruzyny")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("DruzynaId");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("Druzyny");

                    b.HasData(
                        new
                        {
                            DruzynaId = 1,
                            Budzet = 100,
                            NazwaDruzyny = "Drużyna A",
                            UzytkownikId = 1
                        },
                        new
                        {
                            DruzynaId = 2,
                            Budzet = 100,
                            NazwaDruzyny = "Drużyna B",
                            UzytkownikId = 2
                        },
                        new
                        {
                            DruzynaId = 3,
                            Budzet = 100,
                            NazwaDruzyny = "Drużyna C",
                            UzytkownikId = 3
                        });
                });

            modelBuilder.Entity("FantasyApp.Models.Klub", b =>
                {
                    b.Property<int>("KlubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KlubId"), 1L, 1);

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KlubId");

                    b.ToTable("Kluby");

                    b.HasData(
                        new
                        {
                            KlubId = 1,
                            Nazwa = "Lech Poznań"
                        },
                        new
                        {
                            KlubId = 2,
                            Nazwa = "Raków Częstochowa"
                        },
                        new
                        {
                            KlubId = 3,
                            Nazwa = "Jagiellonia Białystok"
                        },
                        new
                        {
                            KlubId = 4,
                            Nazwa = "Legia Warszawa"
                        },
                        new
                        {
                            KlubId = 5,
                            Nazwa = "Cracovia"
                        },
                        new
                        {
                            KlubId = 6,
                            Nazwa = "Górnik Zabrze"
                        },
                        new
                        {
                            KlubId = 7,
                            Nazwa = "Motor Lublin"
                        },
                        new
                        {
                            KlubId = 8,
                            Nazwa = "Pogoń Szczecin"
                        },
                        new
                        {
                            KlubId = 9,
                            Nazwa = "Widzew Łódź"
                        },
                        new
                        {
                            KlubId = 10,
                            Nazwa = "GKS Katowice"
                        },
                        new
                        {
                            KlubId = 11,
                            Nazwa = "Piast Gliwice"
                        },
                        new
                        {
                            KlubId = 12,
                            Nazwa = "Radomiak Radom"
                        },
                        new
                        {
                            KlubId = 13,
                            Nazwa = "Stal Mielec"
                        },
                        new
                        {
                            KlubId = 14,
                            Nazwa = "Zagłębie Lubin"
                        },
                        new
                        {
                            KlubId = 15,
                            Nazwa = "Puszcza Niepołomice"
                        },
                        new
                        {
                            KlubId = 16,
                            Nazwa = "Korona Kielce"
                        },
                        new
                        {
                            KlubId = 17,
                            Nazwa = "Lechia Gdańsk"
                        },
                        new
                        {
                            KlubId = 18,
                            Nazwa = "Śląsk Wrocław"
                        });
                });

            modelBuilder.Entity("FantasyApp.Models.SkladDruzyny", b =>
                {
                    b.Property<int>("DruzynaId")
                        .HasColumnType("int");

                    b.Property<int>("ZawodnikId")
                        .HasColumnType("int");

                    b.HasKey("DruzynaId", "ZawodnikId");

                    b.HasIndex("ZawodnikId");

                    b.ToTable("SkladDruzyny");

                    b.HasData(
                        new
                        {
                            DruzynaId = 1,
                            ZawodnikId = 1
                        },
                        new
                        {
                            DruzynaId = 1,
                            ZawodnikId = 3
                        },
                        new
                        {
                            DruzynaId = 2,
                            ZawodnikId = 2
                        },
                        new
                        {
                            DruzynaId = 2,
                            ZawodnikId = 4
                        },
                        new
                        {
                            DruzynaId = 3,
                            ZawodnikId = 5
                        },
                        new
                        {
                            DruzynaId = 3,
                            ZawodnikId = 7
                        });
                });

            modelBuilder.Entity("FantasyApp.Models.StatystykiZawodnikow", b =>
                {
                    b.Property<int>("StatystykiZawodnikowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatystykiZawodnikowId"), 1L, 1);

                    b.Property<int>("Asysty")
                        .HasColumnType("int");

                    b.Property<int>("Bramki")
                        .HasColumnType("int");

                    b.Property<int>("CzerwoneKartki")
                        .HasColumnType("int");

                    b.Property<int>("DruzynaId")
                        .HasColumnType("int");

                    b.Property<int>("KarneSpowodowane")
                        .HasColumnType("int");

                    b.Property<int>("KarneWywalczone")
                        .HasColumnType("int");

                    b.Property<int>("KarneZmarnowane")
                        .HasColumnType("int");

                    b.Property<int>("Punkty")
                        .HasColumnType("int");

                    b.Property<int>("StrzalyObronione")
                        .HasColumnType("int");

                    b.Property<int>("ZawodnikId")
                        .HasColumnType("int");

                    b.Property<int>("ZolteKartki")
                        .HasColumnType("int");

                    b.HasKey("StatystykiZawodnikowId");

                    b.HasIndex("DruzynaId");

                    b.HasIndex("ZawodnikId");

                    b.ToTable("StatystykiZawodnikow");

                    b.HasData(
                        new
                        {
                            StatystykiZawodnikowId = 1,
                            Asysty = 1,
                            Bramki = 1,
                            CzerwoneKartki = 0,
                            DruzynaId = 1,
                            KarneSpowodowane = 0,
                            KarneWywalczone = 0,
                            KarneZmarnowane = 0,
                            Punkty = 5,
                            StrzalyObronione = 0,
                            ZawodnikId = 1,
                            ZolteKartki = 0
                        },
                        new
                        {
                            StatystykiZawodnikowId = 2,
                            Asysty = 1,
                            Bramki = 1,
                            CzerwoneKartki = 0,
                            DruzynaId = 2,
                            KarneSpowodowane = 0,
                            KarneWywalczone = 0,
                            KarneZmarnowane = 0,
                            Punkty = 5,
                            StrzalyObronione = 0,
                            ZawodnikId = 2,
                            ZolteKartki = 0
                        },
                        new
                        {
                            StatystykiZawodnikowId = 3,
                            Asysty = 1,
                            Bramki = 1,
                            CzerwoneKartki = 0,
                            DruzynaId = 1,
                            KarneSpowodowane = 0,
                            KarneWywalczone = 0,
                            KarneZmarnowane = 0,
                            Punkty = 5,
                            StrzalyObronione = 0,
                            ZawodnikId = 3,
                            ZolteKartki = 0
                        });
                });

            modelBuilder.Entity("FantasyApp.Models.Transfer", b =>
                {
                    b.Property<int>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransferId"), 1L, 1);

                    b.Property<int>("DruzynaId")
                        .HasColumnType("int");

                    b.Property<string>("TypTransferu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZawodnikId")
                        .HasColumnType("int");

                    b.HasKey("TransferId");

                    b.HasIndex("DruzynaId");

                    b.HasIndex("ZawodnikId");

                    b.ToTable("Transfery");

                    b.HasData(
                        new
                        {
                            TransferId = 1,
                            DruzynaId = 1,
                            TypTransferu = "Kupno",
                            ZawodnikId = 1
                        },
                        new
                        {
                            TransferId = 2,
                            DruzynaId = 1,
                            TypTransferu = "Kupno",
                            ZawodnikId = 3
                        },
                        new
                        {
                            TransferId = 3,
                            DruzynaId = 2,
                            TypTransferu = "Kupno",
                            ZawodnikId = 4
                        });
                });

            modelBuilder.Entity("FantasyApp.Models.Uzytkownik", b =>
                {
                    b.Property<int>("UzytkownikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UzytkownikId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Punkty")
                        .HasColumnType("int");

                    b.HasKey("UzytkownikId");

                    b.ToTable("Uzytkownicy");

                    b.HasData(
                        new
                        {
                            UzytkownikId = 1,
                            Email = "user1@example.com",
                            Haslo = "password1",
                            Login = "user1",
                            Punkty = 0
                        },
                        new
                        {
                            UzytkownikId = 2,
                            Email = "user2@example.com",
                            Haslo = "password2",
                            Login = "user2",
                            Punkty = 0
                        },
                        new
                        {
                            UzytkownikId = 3,
                            Email = "user3@example.com",
                            Haslo = "password3",
                            Login = "user3",
                            Punkty = 0
                        });
                });

            modelBuilder.Entity("FantasyApp.Models.Zawodnik", b =>
                {
                    b.Property<int>("ZawodnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZawodnikId"), 1L, 1);

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KlubId")
                        .HasColumnType("int");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pozycja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Punkty")
                        .HasColumnType("int");

                    b.HasKey("ZawodnikId");

                    b.HasIndex("KlubId");

                    b.ToTable("Zawodnicy");

                    b.HasData(
                        new
                        {
                            ZawodnikId = 1,
                            Cena = 6.5m,
                            KlubId = 1,
                            Nazwisko = "Mrozek",
                            Pozycja = "Bramkarz",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 2,
                            Cena = 5m,
                            KlubId = 1,
                            Nazwisko = "Bednarek",
                            Pozycja = "Bramkarz",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 3,
                            Cena = 8.5m,
                            KlubId = 1,
                            Nazwisko = "Pereira",
                            Pozycja = "Obrońca",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 4,
                            Cena = 7m,
                            KlubId = 1,
                            Nazwisko = "Gurgul",
                            Pozycja = "Obrońca",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 5,
                            Cena = 6.5m,
                            KlubId = 1,
                            Nazwisko = "Milic",
                            Pozycja = "Obrońca",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 6,
                            Cena = 6.5m,
                            KlubId = 1,
                            Nazwisko = "Douglas",
                            Pozycja = "Obrońca",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 7,
                            Cena = 5.5m,
                            KlubId = 1,
                            Nazwisko = "Salamon",
                            Pozycja = "Obrońca",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 8,
                            Cena = 4.5m,
                            KlubId = 1,
                            Nazwisko = "Andersson",
                            Pozycja = "Obrońca",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 9,
                            Cena = 4.5m,
                            KlubId = 1,
                            Nazwisko = "Pingot",
                            Pozycja = "Obrońca",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 10,
                            Cena = 4.5m,
                            KlubId = 1,
                            Nazwisko = "Hoffman",
                            Pozycja = "Obrońca",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 11,
                            Cena = 4.5m,
                            KlubId = 1,
                            Nazwisko = "Mońka",
                            Pozycja = "Obrońca",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 12,
                            Cena = 4m,
                            KlubId = 1,
                            Nazwisko = "Dagerstal",
                            Pozycja = "Obrońca",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 13,
                            Cena = 4m,
                            KlubId = 1,
                            Nazwisko = "Wichtowski",
                            Pozycja = "Obrońca",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 14,
                            Cena = 10.5m,
                            KlubId = 1,
                            Nazwisko = "Sousa",
                            Pozycja = "Pomocnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 15,
                            Cena = 8.5m,
                            KlubId = 1,
                            Nazwisko = "Walemark",
                            Pozycja = "Pomocnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 16,
                            Cena = 7m,
                            KlubId = 1,
                            Nazwisko = "Hotic",
                            Pozycja = "Pomocnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 17,
                            Cena = 7m,
                            KlubId = 1,
                            Nazwisko = "Hakans",
                            Pozycja = "Pomocnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 18,
                            Cena = 7m,
                            KlubId = 1,
                            Nazwisko = "Gholizadeh",
                            Pozycja = "Pomocnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 19,
                            Cena = 6m,
                            KlubId = 1,
                            Nazwisko = "Kozubal",
                            Pozycja = "Pomocnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 20,
                            Cena = 5m,
                            KlubId = 1,
                            Nazwisko = "Murawski",
                            Pozycja = "Pomocnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 21,
                            Cena = 5m,
                            KlubId = 1,
                            Nazwisko = "Jagiełło",
                            Pozycja = "Pomocnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 22,
                            Cena = 4.5m,
                            KlubId = 1,
                            Nazwisko = "Ba Loua",
                            Pozycja = "Pomocnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 23,
                            Cena = 4m,
                            KlubId = 1,
                            Nazwisko = "S. Loncar",
                            Pozycja = "Pomocnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 24,
                            Cena = 4m,
                            KlubId = 1,
                            Nazwisko = "Lisman",
                            Pozycja = "Pomocnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 25,
                            Cena = 14m,
                            KlubId = 1,
                            Nazwisko = "Ishak",
                            Pozycja = "Napastnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 26,
                            Cena = 6m,
                            KlubId = 1,
                            Nazwisko = "Szymczak",
                            Pozycja = "Napastnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 27,
                            Cena = 5.5m,
                            KlubId = 1,
                            Nazwisko = "Fiabema",
                            Pozycja = "Napastnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 28,
                            Cena = 5.5m,
                            KlubId = 2,
                            Nazwisko = "Abramowicz",
                            Pozycja = "Bramkarz",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 29,
                            Cena = 4.5m,
                            KlubId = 2,
                            Nazwisko = "Stryjek",
                            Pozycja = "Bramkarz",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 30,
                            Cena = 3m,
                            KlubId = 2,
                            Nazwisko = "Zynel",
                            Pozycja = "Bramkarz",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 31,
                            Cena = 3m,
                            KlubId = 2,
                            Nazwisko = "Piekutkowski",
                            Pozycja = "Bramkarz",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 32,
                            Cena = 3m,
                            KlubId = 2,
                            Nazwisko = "Suchocki",
                            Pozycja = "Bramkarz",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 33,
                            Cena = 6.5m,
                            KlubId = 2,
                            Nazwisko = "Moutinho",
                            Pozycja = "Obrońca",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 34,
                            Cena = 6m,
                            KlubId = 2,
                            Nazwisko = "Sacek",
                            Pozycja = "Obrońca",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 35,
                            Cena = 5.5m,
                            KlubId = 2,
                            Nazwisko = "Skrzypczak",
                            Pozycja = "Obrońca",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 36,
                            Cena = 5.5m,
                            KlubId = 2,
                            Nazwisko = "Dieguez",
                            Pozycja = "Obrońca",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 37,
                            Cena = 5m,
                            KlubId = 2,
                            Nazwisko = "Stojinovic",
                            Pozycja = "Obrońca",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 38,
                            Cena = 4.5m,
                            KlubId = 2,
                            Nazwisko = "Tomas Silva",
                            Pozycja = "Obrońca",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 39,
                            Cena = 4.5m,
                            KlubId = 2,
                            Nazwisko = "Haliti",
                            Pozycja = "Obrońca",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 40,
                            Cena = 4m,
                            KlubId = 2,
                            Nazwisko = "Polak",
                            Pozycja = "Obrońca",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 41,
                            Cena = 4.5m,
                            KlubId = 2,
                            Nazwisko = "Kovacik",
                            Pozycja = "Obrońca",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 42,
                            Cena = 9m,
                            KlubId = 2,
                            Nazwisko = "Hansen",
                            Pozycja = "Pomocnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 43,
                            Cena = 8m,
                            KlubId = 2,
                            Nazwisko = "Miki",
                            Pozycja = "Pomocnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 44,
                            Cena = 8m,
                            KlubId = 2,
                            Nazwisko = "Curlinov",
                            Pozycja = "Pomocnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 45,
                            Cena = 6m,
                            KlubId = 2,
                            Nazwisko = "Kubicki",
                            Pozycja = "Pomocnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 46,
                            Cena = 6m,
                            KlubId = 2,
                            Nazwisko = "Nene",
                            Pozycja = "Pomocnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 47,
                            Cena = 5.5m,
                            KlubId = 2,
                            Nazwisko = "Romanczuk",
                            Pozycja = "Pomocnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 48,
                            Cena = 4.5m,
                            KlubId = 2,
                            Nazwisko = "Listkowski",
                            Pozycja = "Pomocnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 49,
                            Cena = 4.5m,
                            KlubId = 2,
                            Nazwisko = "Nguiamba",
                            Pozycja = "Pomocnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 50,
                            Cena = 3m,
                            KlubId = 2,
                            Nazwisko = "Kozłowski",
                            Pozycja = "Pomocnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 51,
                            Cena = 3m,
                            KlubId = 2,
                            Nazwisko = "Stypułkowski",
                            Pozycja = "Pomocnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 52,
                            Cena = 12m,
                            KlubId = 2,
                            Nazwisko = "Imaz",
                            Pozycja = "Napastnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 53,
                            Cena = 10m,
                            KlubId = 2,
                            Nazwisko = "Pululu",
                            Pozycja = "Napastnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 54,
                            Cena = 6.5m,
                            KlubId = 2,
                            Nazwisko = "Fadiga",
                            Pozycja = "Napastnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 55,
                            Cena = 4.5m,
                            KlubId = 2,
                            Nazwisko = "Rybak",
                            Pozycja = "Napastnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 56,
                            Cena = 3m,
                            KlubId = 2,
                            Nazwisko = "Pietuszewski",
                            Pozycja = "Napastnik",
                            Punkty = 0
                        },
                        new
                        {
                            ZawodnikId = 57,
                            Cena = 3m,
                            KlubId = 2,
                            Nazwisko = "Wojdakowski",
                            Pozycja = "Napastnik",
                            Punkty = 0
                        });
                });

            modelBuilder.Entity("FantasyApp.Models.Druzyna", b =>
                {
                    b.HasOne("FantasyApp.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("Druzyny")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("FantasyApp.Models.SkladDruzyny", b =>
                {
                    b.HasOne("FantasyApp.Models.Druzyna", "Druzyna")
                        .WithMany("SkladDruzyny")
                        .HasForeignKey("DruzynaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyApp.Models.Zawodnik", "Zawodnik")
                        .WithMany("SkladDruzyny")
                        .HasForeignKey("ZawodnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Druzyna");

                    b.Navigation("Zawodnik");
                });

            modelBuilder.Entity("FantasyApp.Models.StatystykiZawodnikow", b =>
                {
                    b.HasOne("FantasyApp.Models.Druzyna", "Druzyna")
                        .WithMany("Statystyki")
                        .HasForeignKey("DruzynaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyApp.Models.Zawodnik", "Zawodnik")
                        .WithMany("Statystyki")
                        .HasForeignKey("ZawodnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Druzyna");

                    b.Navigation("Zawodnik");
                });

            modelBuilder.Entity("FantasyApp.Models.Transfer", b =>
                {
                    b.HasOne("FantasyApp.Models.Druzyna", "Druzyna")
                        .WithMany("Transfery")
                        .HasForeignKey("DruzynaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyApp.Models.Zawodnik", "Zawodnik")
                        .WithMany("Transfery")
                        .HasForeignKey("ZawodnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Druzyna");

                    b.Navigation("Zawodnik");
                });

            modelBuilder.Entity("FantasyApp.Models.Zawodnik", b =>
                {
                    b.HasOne("FantasyApp.Models.Klub", "Klub")
                        .WithMany("Zawodnicy")
                        .HasForeignKey("KlubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klub");
                });

            modelBuilder.Entity("FantasyApp.Models.Druzyna", b =>
                {
                    b.Navigation("SkladDruzyny");

                    b.Navigation("Statystyki");

                    b.Navigation("Transfery");
                });

            modelBuilder.Entity("FantasyApp.Models.Klub", b =>
                {
                    b.Navigation("Zawodnicy");
                });

            modelBuilder.Entity("FantasyApp.Models.Uzytkownik", b =>
                {
                    b.Navigation("Druzyny");
                });

            modelBuilder.Entity("FantasyApp.Models.Zawodnik", b =>
                {
                    b.Navigation("SkladDruzyny");

                    b.Navigation("Statystyki");

                    b.Navigation("Transfery");
                });
#pragma warning restore 612, 618
        }
    }
}
